# This creates a service account called tiller with cluster-admin privilages. It
# is intended to be used to give helm the necessary privilages to grant RBAC
# roles to Sourcegraph which are not possible via the default service account.
#
#   helm init --service-account tiller
#
# https://github.com/kubernetes/helm/blob/v2.8.2/docs/rbac.md#example-service-account-with-cluster-admin-role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
